# -*- coding: utf-8 -*-
"""321 final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nfj0SzfHP10iFl594bceLBmYZvAGBRHh
"""

!pip install ultralytics roboflow

from roboflow import Roboflow

rf = Roboflow(api_key="JgoZJQbXxn7GH09lB2QV")  # 🔁 Put your actual key here
project = rf.workspace("321-9ilmb").project("crack-c6v7t-3s7jy")
version = project.version(1)
dataset = version.download("yolov8")

!ls crack-1

from ultralytics import YOLO

model = YOLO("yolov8n.pt")  # You can use yolov8s.pt for better accuracy

model.train(data="crack-1/data.yaml", epochs=50, imgsz=640)

from ultralytics import YOLO

model = YOLO("yolov8n.pt")

model.train(data="/content/crack-1/data.yaml", epochs=50, imgsz=640)

from google.colab import drive
drive.mount('/content/drive')

from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_true, y_pred)
print("Accuracy:", accuracy)

